var hierarchy =
[
    [ "MediaController::GstWrapper::Builder", "../MediaController/class_media_controller_1_1_gst_wrapper_1_1_builder.html", null ],
    [ "CPPCli::Clip", "../CSharpWrapper/class_c_p_p_cli_1_1_clip.html", null ],
    [ "MediaController::Rtsp::Commands", "../MediaController/class_media_controller_1_1_rtsp_1_1_commands.html", null ],
    [ "CPPCli::DataInterface", "../CSharpWrapper/class_c_p_p_cli_1_1_data_interface.html", null ],
    [ "CPPCli::DataSession", "../CSharpWrapper/class_c_p_p_cli_1_1_data_session.html", null ],
    [ "CPPCli::DataSource", "../CSharpWrapper/class_c_p_p_cli_1_1_data_source.html", null ],
    [ "CPPCli::Device", "../CSharpWrapper/class_c_p_p_cli_1_1_device.html", null ],
    [ "CPPCli::Event", "../CSharpWrapper/class_c_p_p_cli_1_1_event.html", null ],
    [ "CPPCli::Export", "../CSharpWrapper/class_c_p_p_cli_1_1_export.html", null ],
    [ "CPPCli::ExportClip", "../CSharpWrapper/class_c_p_p_cli_1_1_export_clip.html", null ],
    [ "MediaController::GstVars", "../MediaController/struct_media_controller_1_1_gst_vars.html", null ],
    [ "MediaController::GstWrapper", "../MediaController/class_media_controller_1_1_gst_wrapper.html", null ],
    [ "MediaController::IStream", "../MediaController/class_media_controller_1_1_i_stream.html", [
      [ "MediaController::IController", "../MediaController/class_media_controller_1_1_i_controller.html", [
        [ "MediaController::Controller", "../MediaController/class_media_controller_1_1_controller.html", null ]
      ] ],
      [ "MediaController::StreamBase", "../MediaController/class_media_controller_1_1_stream_base.html", [
        [ "MediaController::MjpegPull::Stream", "../MediaController/class_media_controller_1_1_mjpeg_pull_1_1_stream.html", null ],
        [ "MediaController::Rtsp::Stream", "../MediaController/class_media_controller_1_1_rtsp_1_1_stream.html", null ]
      ] ]
    ] ],
    [ "VxSdk::IVxClip", "../VxSdk/struct_vx_sdk_1_1_i_vx_clip.html", null ],
    [ "VxSdk::IVxDataInterface", "../VxSdk/struct_vx_sdk_1_1_i_vx_data_interface.html", null ],
    [ "VxSdk::IVxDataSession", "../VxSdk/struct_vx_sdk_1_1_i_vx_data_session.html", null ],
    [ "VxSdk::IVxDataSource", "../VxSdk/struct_vx_sdk_1_1_i_vx_data_source.html", null ],
    [ "VxSdk::IVxDevice", "../VxSdk/struct_vx_sdk_1_1_i_vx_device.html", null ],
    [ "VxSdk::IVxEvent", "../VxSdk/struct_vx_sdk_1_1_i_vx_event.html", null ],
    [ "VxSdk::IVxExport", "../VxSdk/struct_vx_sdk_1_1_i_vx_export.html", null ],
    [ "VxSdk::IVxExportClip", "../VxSdk/struct_vx_sdk_1_1_i_vx_export_clip.html", null ],
    [ "VxSdk::IVxPattern", "../VxSdk/struct_vx_sdk_1_1_i_vx_pattern.html", null ],
    [ "VxSdk::IVxPreset", "../VxSdk/struct_vx_sdk_1_1_i_vx_preset.html", null ],
    [ "VxSdk::IVxPtzController", "../VxSdk/struct_vx_sdk_1_1_i_vx_ptz_controller.html", null ],
    [ "VxSdk::IVxSituation", "../VxSdk/struct_vx_sdk_1_1_i_vx_situation.html", null ],
    [ "VxSdk::IVxSystem", "../VxSdk/struct_vx_sdk_1_1_i_vx_system.html", null ],
    [ "MediaController::Rtsp::KeepAlive", "../MediaController/class_media_controller_1_1_rtsp_1_1_keep_alive.html", null ],
    [ "CPPCli::MediaControl", "../CSharpWrapper/class_c_p_p_cli_1_1_media_control.html", null ],
    [ "MediaController::Rtsp::MediaDescription", "../MediaController/struct_media_controller_1_1_rtsp_1_1_media_description.html", null ],
    [ "CPPCli::MediaEvent", "../CSharpWrapper/class_c_p_p_cli_1_1_media_event.html", null ],
    [ "MediaController::MediaRequest", "../MediaController/struct_media_controller_1_1_media_request.html", null ],
    [ "CPPCli::NewEvent", "../CSharpWrapper/class_c_p_p_cli_1_1_new_event.html", null ],
    [ "CPPCli::NewExport", "../CSharpWrapper/class_c_p_p_cli_1_1_new_export.html", null ],
    [ "CPPCli::NewExportClip", "../CSharpWrapper/class_c_p_p_cli_1_1_new_export_clip.html", null ],
    [ "CPPCli::NewSituation", "../CSharpWrapper/class_c_p_p_cli_1_1_new_situation.html", null ],
    [ "CPPCli::Pattern", "../CSharpWrapper/class_c_p_p_cli_1_1_pattern.html", null ],
    [ "CPPCli::Preset", "../CSharpWrapper/class_c_p_p_cli_1_1_preset.html", null ],
    [ "CPPCli::PtzController", "../CSharpWrapper/class_c_p_p_cli_1_1_ptz_controller.html", null ],
    [ "MediaController::Rtsp::Response", "../MediaController/struct_media_controller_1_1_rtsp_1_1_response.html", null ],
    [ "CPPCli::Results", "../CSharpWrapper/class_c_p_p_cli_1_1_results.html", null ],
    [ "MediaController::Rtsp::SdpParser", "../MediaController/class_media_controller_1_1_rtsp_1_1_sdp_parser.html", null ],
    [ "CPPCli::Situation", "../CSharpWrapper/class_c_p_p_cli_1_1_situation.html", null ],
    [ "MediaController::StreamFactory", "../MediaController/class_media_controller_1_1_stream_factory.html", null ],
    [ "MediaController::StreamState", "../MediaController/class_media_controller_1_1_stream_state.html", [
      [ "MediaController::PausedState", "../MediaController/class_media_controller_1_1_paused_state.html", null ],
      [ "MediaController::PlayingState", "../MediaController/class_media_controller_1_1_playing_state.html", null ],
      [ "MediaController::StoppedState", "../MediaController/class_media_controller_1_1_stopped_state.html", null ]
    ] ],
    [ "MediaController::TimestampEvent", "../MediaController/struct_media_controller_1_1_timestamp_event.html", null ],
    [ "CPPCli::Utils", "../CSharpWrapper/class_c_p_p_cli_1_1_utils.html", null ],
    [ "VxSdk::VxAckState", "../VxSdk/struct_vx_sdk_1_1_vx_ack_state.html", null ],
    [ "VxSdk::VxCollection< T >", "../VxSdk/struct_vx_sdk_1_1_vx_collection.html", null ],
    [ "VxSdk::VxCollectionFilter", "../VxSdk/struct_vx_sdk_1_1_vx_collection_filter.html", null ],
    [ "VxSdk::VxCollectionFilterItem", "../VxSdk/struct_vx_sdk_1_1_vx_collection_filter_item.html", null ],
    [ "VxSdk::VxDataSourceType", "../VxSdk/struct_vx_sdk_1_1_vx_data_source_type.html", null ],
    [ "VxSdk::VxDeviceState", "../VxSdk/struct_vx_sdk_1_1_vx_device_state.html", null ],
    [ "VxSdk::VxDeviceType", "../VxSdk/struct_vx_sdk_1_1_vx_device_type.html", null ],
    [ "VxSdk::VxExportFormat", "../VxSdk/struct_vx_sdk_1_1_vx_export_format.html", null ],
    [ "VxSdk::VxExportStatus", "../VxSdk/struct_vx_sdk_1_1_vx_export_status.html", null ],
    [ "VxSdk::VxFocusDirection", "../VxSdk/struct_vx_sdk_1_1_vx_focus_direction.html", null ],
    [ "VxSdk::VxIrisDirection", "../VxSdk/struct_vx_sdk_1_1_vx_iris_direction.html", null ],
    [ "VxSdk::VxKvObject", "../VxSdk/struct_vx_sdk_1_1_vx_kv_object.html", null ],
    [ "VxSdk::VxLoginInfo", "../VxSdk/struct_vx_sdk_1_1_vx_login_info.html", null ],
    [ "VxSdk::VxNewEvent", "../VxSdk/struct_vx_sdk_1_1_vx_new_event.html", null ],
    [ "VxSdk::VxNewExport", "../VxSdk/struct_vx_sdk_1_1_vx_new_export.html", null ],
    [ "VxSdk::VxNewExportClip", "../VxSdk/struct_vx_sdk_1_1_vx_new_export_clip.html", null ],
    [ "VxSdk::VxNewSituation", "../VxSdk/struct_vx_sdk_1_1_vx_new_situation.html", null ],
    [ "VxSdk::VxRecordingFramerate", "../VxSdk/struct_vx_sdk_1_1_vx_recording_framerate.html", null ],
    [ "VxSdk::VxRecordingType", "../VxSdk/struct_vx_sdk_1_1_vx_recording_type.html", null ],
    [ "VxSdk::VxResult", "../VxSdk/struct_vx_sdk_1_1_vx_result.html", null ],
    [ "VxSdk::VxRetentionPriority", "../VxSdk/struct_vx_sdk_1_1_vx_retention_priority.html", null ],
    [ "VxSdk::VxStreamProtocol", "../VxSdk/struct_vx_sdk_1_1_vx_stream_protocol.html", null ],
    [ "CPPCli::VXSystem", "../CSharpWrapper/class_c_p_p_cli_1_1_v_x_system.html", null ],
    [ "VxSdk::VxZoomDirection", "../VxSdk/struct_vx_sdk_1_1_vx_zoom_direction.html", null ],
    [ "T", null, null ]
];