/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_JDataSource */

#ifndef _Included_javasample_JDataSource
#define _Included_javasample_JDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasample_JDataSource
 * Method:    IsPTZEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JDataSource_IsPTZEnabled
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDataSource
 * Method:    GetPTZController
 * Signature: ()Ljavasample/JPTZController;
 */
JNIEXPORT jobject JNICALL Java_javasample_JDataSource_GetPTZController
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDataSource
 * Method:    GetClips
 * Signature: ()[Ljavasample/JClip;
 */
JNIEXPORT jobjectArray JNICALL Java_javasample_JDataSource_GetClips
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDataSource
 * Method:    GetDataInterfaces
 * Signature: ()[Ljavasample/JDataInterface;
 */
JNIEXPORT jobjectArray JNICALL Java_javasample_JDataSource_GetDataInterfaces
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDataSource
 * Method:    GetRTSPEndpoint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javasample_JDataSource_GetRTSPEndpoint
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDataSource
 * Method:    CreateMJPEGSession
 * Signature: ()Ljavasample/JDataSession;
 */
JNIEXPORT jobject JNICALL Java_javasample_JDataSource_CreateMJPEGSession
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
