/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_Win32 */

#ifndef _Included_javasample_Win32
#define _Included_javasample_Win32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasample_Win32
 * Method:    getWindowHandle
 * Signature: (Ljava/awt/Component;)I
 */
JNIEXPORT jint JNICALL Java_javasample_Win32_getWindowHandle
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
