/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_JMediaControl */

#ifndef _Included_javasample_JMediaControl
#define _Included_javasample_JMediaControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasample_JMediaControl
 * Method:    InvokeMediaController
 * Signature: (Ljavasample/JDataSource;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JMediaControl_InvokeMediaController
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     javasample_JMediaControl
 * Method:    SetDataSource
 * Signature: (Ljavasample/JDataSource;I)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JMediaControl_SetDataSource
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     javasample_JMediaControl
 * Method:    SetVideoWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_SetVideoWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javasample_JMediaControl
 * Method:    SubscribeTimeStampEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_SubscribeTimeStampEvents
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JMediaControl
 * Method:    UnSubscribeTimeStampEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_UnSubscribeTimeStampEvents
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JMediaControl
 * Method:    Play
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_Play
  (JNIEnv *, jobject, jint);

/*
 * Class:     javasample_JMediaControl
 * Method:    Pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_Pause
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JMediaControl
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_Stop
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JMediaControl
 * Method:    GotoLive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_GotoLive
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JMediaControl
 * Method:    Seek
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_Seek
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javasample_JMediaControl
 * Method:    Delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javasample_JMediaControl_Delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
