/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_JSystem */

#ifndef _Included_javasample_JSystem
#define _Included_javasample_JSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasample_JSystem
 * Method:    Connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_Connect
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
* Class:     javasample_JSystem
* Method:    Disconnect
* Signature: ()[]
*/
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_Disconnect(JNIEnv *, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    GetDevices
 * Signature: ()[Ljavasample/JDevice;
 */
JNIEXPORT jobjectArray JNICALL Java_javasample_JSystem_GetDevices
  (JNIEnv *, jobject);

/*
* Class:     javasample_JSystem
* Method:    GetExports
* Signature: ()[Ljavasample/JExport;
*/
JNIEXPORT jobjectArray JNICALL Java_javasample_JSystem_GetExports
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    CreateExport
 * Signature: ([Ljavasample/JClip;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javasample_JSystem_CreateExport
  (JNIEnv *, jobject, jobjectArray, jstring, jstring, jstring);

/*
 * Class:     javasample_JSystem
 * Method:    DeleteExport
 * Signature: (Ljavasample/JExport;)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_DeleteExport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    GetSituations
 * Signature: ()[Ljavasample/JSituation;
 */
JNIEXPORT jobjectArray JNICALL Java_javasample_JSystem_GetSituations
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    InsertNewEvent
 * Signature: (Ljavasample/JNewEvent;Ljava/util/Hashtable;)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_InsertNewEvent
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    SubscribeEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_SubscribeEvents
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    UnsubscribeEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_UnsubscribeEvents
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    DeleteSituation
 * Signature: (Ljavasample/JSituation;)Z
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_DeleteSituation
  (JNIEnv *, jobject, jobject);

/*
 * Class:     javasample_JSystem
 * Method:    AddSituation
 * Signature: (Ljavasample/JSituation;)V
 */
JNIEXPORT jboolean JNICALL Java_javasample_JSystem_AddSituation
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
