/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_JDevice */

#ifndef _Included_javasample_JDevice
#define _Included_javasample_JDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javasample_JDevice
 * Method:    GetDataSources
 * Signature: ()[Ljavasample/JDataSource;
 */
JNIEXPORT jobjectArray JNICALL Java_javasample_JDevice_GetDataSources
  (JNIEnv *, jobject);

/*
 * Class:     javasample_JDevice
 * Method:    GetDeviceHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javasample_JDevice_GetDeviceHandle
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
