/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javasample_JEvent */

#ifndef _Included_javasample_JEvent
#define _Included_javasample_JEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
